@extends('layouts.app')
@section('title', isset($registrationCategory) ? 'Edit Registration Category' : 'Add Registration Category')
@section('content')
@php($editing = isset($registrationCategory))
<div class="app-title"><div><h1><i class="fa fa-id-badge"></i> Registration Categories</h1></div><ul class="app-breadcrumb breadcrumb"><li class="breadcrumb-item">Admin</li><li class="breadcrumb-item">Registration Categories</li><li class="breadcrumb-item active">{{ $editing ? 'Edit' : 'Create' }}</li></ul></div>
<form method="POST" action="{{ $editing ? route('admin.registration-categories.update', $registrationCategory) : route('admin.registration-categories.store') }}">@csrf @if($editing) @method('PUT') @endif
<div class="tile"><div class="tile-title-w-btn"><h3 class="title">{{ $editing ? 'Edit '.$registrationCategory->name : 'Add Registration Category' }}</h3><a class="btn btn-primary btn-sm" href="{{ route('admin.registration-categories.index') }}"><i class="fa fa-list"></i> See List</a></div><div class="tile-body"><div class="row"><div class="form-group col-md-6"><label>Category Name <span class="text-danger">*</span></label><input class="form-control" name="name" required value="{{ old('name', $registrationCategory->name ?? '') }}" placeholder="e.g. Officer">@error('name')<small class="text-danger">{{ $message }}</small>@enderror</div><div class="form-group col-md-6"><label>Slug <small class="text-muted">(optional)</small></label><input class="form-control" name="slug" value="{{ old('slug', $registrationCategory->slug ?? '') }}" placeholder="Auto-generated from the name">@error('slug')<small class="text-danger">{{ $message }}</small>@enderror</div><div class="form-group col-md-8"><label>Description</label><textarea class="form-control" rows="4" name="description" placeholder="Optional category description">{{ old('description', $registrationCategory->description ?? '') }}</textarea></div><div class="form-group col-md-4"><label>Status</label><select class="form-control" name="is_active"><option value="1" @selected(old('is_active', isset($registrationCategory) ? (int)$registrationCategory->is_active : 1) === 1)>Active</option><option value="0" @selected(old('is_active', isset($registrationCategory) ? (int)$registrationCategory->is_active : 1) === 0)>Inactive</option></select></div></div></div><div class="tile-footer"><button class="btn btn-primary"><i class="fa fa-save"></i> {{ $editing ? 'Update Category' : 'Create Category' }}</button></div></div>
</form>
@endsection
