@extends('layouts.app')
@section('title', isset($shopCategory) ? 'Edit Product Category' : 'Add Product Category')
@section('content')
@php($editing = isset($shopCategory))
<div class="app-title"><div><h1><i class="fa fa-tags"></i> Product Categories</h1></div><ul class="app-breadcrumb breadcrumb"><li class="breadcrumb-item">E-Shop</li><li class="breadcrumb-item">Categories</li><li class="breadcrumb-item active">{{ $editing ? 'Edit' : 'Create' }}</li></ul></div>
<form method="POST" action="{{ $editing ? route('admin.e-shop.categories.update', $shopCategory) : route('admin.e-shop.categories.store') }}">@csrf @if($editing) @method('PUT') @endif
<div class="tile"><div class="tile-title-w-btn"><h3 class="title">{{ $editing ? 'Edit '.$shopCategory->name : 'Add Product Category' }}</h3><a class="btn btn-primary btn-sm" href="{{ route('admin.e-shop.categories.index') }}"><i class="fa fa-list"></i> See List</a></div><div class="tile-body"><div class="row"><div class="form-group col-md-6"><label>Category Name <span class="text-danger">*</span></label><input class="form-control" name="name" required value="{{ old('name', $shopCategory->name ?? '') }}" placeholder="e.g. Home Appliances">@error('name')<small class="text-danger">{{ $message }}</small>@enderror</div><div class="form-group col-md-6"><label>Status</label><select class="form-control" name="is_active"><option value="1" @selected(old('is_active', isset($shopCategory) ? (int) $shopCategory->is_active : 1) === 1)>Active</option><option value="0" @selected(old('is_active', isset($shopCategory) ? (int) $shopCategory->is_active : 1) === 0)>Inactive</option></select></div><div class="form-group col-md-12"><label>Description</label><textarea class="form-control" rows="4" name="description">{{ old('description', $shopCategory->description ?? '') }}</textarea>@error('description')<small class="text-danger">{{ $message }}</small>@enderror</div></div></div><div class="tile-footer"><button class="btn btn-primary"><i class="fa fa-save"></i> {{ $editing ? 'Update Category' : 'Create Category' }}</button></div></div>
</form>
@endsection
