@extends('layouts.app')
@section('title', isset($package) ? 'Edit Package' : 'Add Package')
@section('content')
@php($editing = isset($package))
<div class="app-title"><div><h1><i class="fa fa-cubes"></i> Packages</h1></div><ul class="app-breadcrumb breadcrumb"><li class="breadcrumb-item">Admin</li><li class="breadcrumb-item">Packages</li><li class="breadcrumb-item active">{{ $editing ? 'Edit' : 'Create' }}</li></ul></div>
<form method="POST" action="{{ $editing ? route('admin.packages.update', $package) : route('admin.packages.store') }}">@csrf @if($editing) @method('PUT') @endif
<div class="tile"><div class="tile-title-w-btn"><h3 class="title">{{ $editing ? 'Edit '.$package->name : 'Add Package' }}</h3><a class="btn btn-primary btn-sm" href="{{ route('admin.packages.index') }}"><i class="fa fa-list"></i> See List</a></div><div class="tile-body"><div class="row"><div class="form-group col-md-6"><label>Package Name <span class="text-danger">*</span></label><input class="form-control" name="name" required value="{{ old('name', $package->name ?? '') }}" placeholder="e.g. Micro Oven TK 17,500">@error('name')<small class="text-danger">{{ $message }}</small>@enderror</div><div class="form-group col-md-6"><label>Package Level <span class="text-danger">*</span></label><select class="form-control" name="level" required><option value="level_1" @selected(old('level', $package->level ?? 'level_1') === 'level_1')>Level-1</option><option value="level_2" @selected(old('level', $package->level ?? '') === 'level_2')>Level-2</option></select>@error('level')<small class="text-danger">{{ $message }}</small>@enderror</div><div class="form-group col-md-4"><label>Regular Price</label><input class="form-control" type="number" min="0" step="0.01" name="regular_price" value="{{ old('regular_price', $package->regular_price ?? '') }}">@error('regular_price')<small class="text-danger">{{ $message }}</small>@enderror</div><div class="form-group col-md-4"><label>Selling Price</label><input class="form-control" type="number" min="0" step="0.01" name="selling_price" value="{{ old('selling_price', $package->selling_price ?? '') }}">@error('selling_price')<small class="text-danger">{{ $message }}</small>@enderror</div><div class="form-group col-md-4"><label>Display Order</label><input class="form-control" type="number" min="0" name="sort_order" value="{{ old('sort_order', $package->sort_order ?? 0) }}">@error('sort_order')<small class="text-danger">{{ $message }}</small>@enderror</div><div class="form-group col-md-8"><label>Description</label><textarea class="form-control" rows="4" name="description" placeholder="Optional package details">{{ old('description', $package->description ?? '') }}</textarea>@error('description')<small class="text-danger">{{ $message }}</small>@enderror</div><div class="form-group col-md-4"><label>Status</label><select class="form-control" name="is_active"><option value="1" @selected(old('is_active', isset($package) ? (int) $package->is_active : 1) === 1)>Active</option><option value="0" @selected(old('is_active', isset($package) ? (int) $package->is_active : 1) === 0)>Inactive</option></select></div></div></div><div class="tile-footer"><button class="btn btn-primary"><i class="fa fa-save"></i> {{ $editing ? 'Update Package' : 'Create Package' }}</button></div></div>
</form>
@endsection
